### ISSUE TITLE
LXQt theming not respected

### ISSUE THREAD

**Issue by roselorr** [vanilla-wiiu/vanilla#36]
Friend of VoxelTek here - I've noticed that when trying to run Vanilla on my Debian 12 laptop, it doesn't apply the Qt appearance settings set in LXQt, my desktop environment of choice. (Correctly-themed VLC media player for comparison)
![image](https://github.com/vanilla-wiiu/vanilla/assets/158038718/abd21133-83c9-4ace-9f87-999c0200992d)
I don't know if something is broken, or if support needs to be manually added for LXQt or something, or if this is even something that's within Vanilla's control, and I'm hoping someone here might know what's actually happening.

**Comment by itsmattkc** [comment]
I assume this is with the prebuilt release?

This is kind of a limitation of this method of deployment (or arguably deploying on Linux in general). For Qt to use your platform's theme, it needs a plugin (presumably [this one](https://github.com/lxqt/lxqt-qtplugin)). While you would already have this plugin on your system, since the prebuilt release ships with its own Qt in its own environment, it can't see the plugins on your system. In fact, if the Qt versions differ between the release and your distro - which is fairly likely - the plugins can't be loaded even if it could see them.

While it would be possible to include the LXQt plugin in our release, that becomes a slippery slope towards trying to add plugins for *every* desktop environment, and it quickly becomes unwieldy.

The only real solution is to either compile it yourself for your version of Qt, or for your distro to adopt Vanilla in their repositories (effectively tailoring it for your system's Qt too, but someone else compiles it).
