### ISSUE TITLE
Cannot complete initial setup through Vanilla

### ISSUE THREAD

**Issue by JuliaAllen1** [vanilla-wiiu/vanilla#48]
After factory reset on a, to my knowledge unmodified, stock Wii U, no CFW, I cannot complete the initial setup. It gets to the "Your WiiU GamePad is ready. Tap the screen to set up the console." screen, but upon clicking, it shows an error similar to the one encountered upon a CBHC-brick, but with the normal Wii U dialog, rather than the black screen present in any usual 160-0101. 

I don't have an OEM GamePad to verify this, however *before* the factory reset, everything was working normally, no NAND issues or anything. Additionally, there have been at least two other instances of this reported between the MattKC Discord server and RGD, so it appears to be an issue Vanilla-side. Might there be any major differences between the initial setup environment and a Wii U operating normally that cause this?

**Comment by JuliaAllen1** [comment]
https://github.com/user-attachments/assets/a94a0610-16e8-498d-bea8-4a82b8ac93b1

**Comment by JuliaAllen1** [comment]
I think it *might* have something to do with regions? Part of drc-sim's guide recommends specifying a region during initial setup, and regardless of what region I set the GamePad to, it still pairs with my NTSC-U console.

**Comment by itsmattkc** [comment]
This is a semi-known issue. It does appear to be Vanilla-specific, but I don't have a secondary Wii U on hand that I'm willing to factory reset so I can diagnose what the problem is. I'm trying to pick one up ASAP.

It isn't region related, the region lockout occurs later when the console checks for a gamepad firmware update (any region gamepad will sync successfully initially). I believe it's something else, likely command protocol related, but as I've said I haven't been able to do any diagnosing myself yet.

For the time being, drc-sim doesn't appear to be affected by this issue, so it's possible to use it to complete initial setup, and then Vanilla can be used from then onwards.
