### ISSUE TITLE
Internet seems to partially disconnect when using Vanilla

### ISSUE THREAD

**Issue by lunakittyyy** [vanilla-wiiu/vanilla#54]
Not exactly sure what's going on here. I can't access really anything in Firefox, but pinging IP addresses in the terminal seems to work fine.
Maybe NetworkManager is prioritizing the WiFi adapter in some way?
USB WiFi adapter is using the ``rtw_8821cu`` kernel module

![image](https://github.com/user-attachments/assets/58aabbdd-8b19-4e03-862d-433b2c94864f)

I am connecting to the Internet with Ethernet rather than the WiFi adapter.

**Comment by StellaLovesTech** [comment]
i also have this issue, except pinging doesnt even work, whenever i use vanilla my internet just doesnt work at all

**Comment by lunakittyyy** [comment]
Seems like its still my default connection:
![image](https://github.com/user-attachments/assets/971b805d-bc29-46e0-8b4f-3f23ce0fea29)
This time I connected while in a Discord voice channel. Interestingly, I could still talk and hear other people, but I could not send text messages in the server and I couldn't load any new webpages in Firefox.

**Comment by itsmattkc** [comment]
> i also have this issue, except pinging doesnt even work, whenever i use vanilla my internet just doesnt work at all

To be clear, if you usually use Wi-Fi to connect to the internet, this is normal. Your Wi-Fi adapter cannot be connected to the Wii U and your home router at the same time. However, if you're talking about a separate Wi-Fi/ethernet connection and you have similar output from `ip route`, then...

> Seems like its still my default connection:

The issue seems to be that your home network and the Wii U both have the same subnet (`192.168.1.0/24`) and gateway (`192.168.1.0`) and they end up conflicting with each other. Unfortunately I'm not sure there's any great solution to this, we can't do anything about the Wii U's addressing scheme, and while you can almost certainly change your home router's addressing scheme, it's a bit of a pain to do so.

**Comment by lunakittyyy** [comment]
It does seem like that was the issue! After changing my router's IP to ``192.168.2.1`` the connected devices follow suit and allow me to browse the Internet while connected to the Wii U.
![image](https://github.com/user-attachments/assets/141c11ee-f50f-4576-ab55-b57a25ac440a)
