### ISSUE TITLE
Authorization check still runs even if program is run as root

### ISSUE THREAD

**Issue by valerie-tar-gz** [vanilla-wiiu/vanilla#62]
Hi! I've been working on getting this program working in Steam Deck game mode and I _think_ I've figured out why it's not working, even if run as root. 

So, for context I've added the vanilla-gui file as an exception in my sudoers meaning it requires no password to run as root.
 I'd like to say now that from a security standpoint, this is bad. However, this is my Steam deck and I do not care.

 This SHOULD mean it can run as root no problem in game mode, however the program still exits. If I run vanilla-gui (Even as root) in gamescope, it exits with an error about authorization failure. I believe the authorization method failure is still causing the program to crash. So, potentially, if a check was implemented to see if the program already has root access then some kind of preliminary Steam Deck support may be possible.

Sorry if this is way off the mark, I'm new to the project and don't have a Wii U to test on yet and was just going based on my observations.

**Comment by crush-hjtm** [comment]
See here, right after getting root it checks for an authorization method.
![image](https://github.com/user-attachments/assets/f7f6bbd2-e963-4651-be7f-b3281a1d2832)

**Comment by itsmattkc** [comment]
> I believe the authorization method failure is still causing the program to crash. So, potentially, if a check was implemented to see if the program already has root access then some kind of preliminary Steam Deck support may be possible.

I believe that's a red herring - `vanilla-gui` has always been capable of running as root, though it's not generally recommended because it won't automatically have access to things like your user's PulseAudio cookie.

The error message you posted appears to be something similar to that, but with Xorg instead of PulseAudio (i.e. Xorg not having access to your user's session under root). I can recreate it on my end by clearing the `XAUTHORITY` environment variable. I'm not sure how your distro is set up, but here are some potential solutions that may help:

- ["No protocol specified" when running a sudo/su app on Ubuntu Linux](https://stackoverflow.com/questions/48833451/no-protocol-specified-when-running-a-sudo-su-app-on-ubuntu-linux)
- [What is the .Xauthority file?](https://askubuntu.com/a/300737)

**Comment by crush-hjtm** [comment]
Oh ok! Sorry, that'll be my limited knowledge on the issue coming through there. I appreciate the clarification. 

I use Bazzite (Based on Fedora) but I was trying to get Vanilla working under gamescope/gamescope-session which is applicable to SteamOS's game mode.

I'll take another dig at it with what you've told me and see if I can get it working. Thanks again.

**Comment by itsmattkc** [comment]
Merging into #107
